title: leohidalgo.dev
description: ""

author: leohidalgo
email: leohidalgo@protonmail.com
twitter_username: leohidalg0
github_username:  leohidalgo

baseurl: ""
url: "https://leohidalgo.dev"

show_excerpts: true
permalink: /:categories/:title

theme: minima
plugins:
  - jekyll-feed
