title: leohidalgo.dev
author: leohidalgo
email: leohidalgo@protonmail.com
description: ""
baseurl: ""
url: "https://leohidalgo.dev"
twitter_username: leohidalg0
github_username:  leohidalgo
show_excerpts: true

theme: minima
plugins:
  - jekyll-feed
